# Generated by Django 5.2.8 on 2025-11-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=155)),
                ('numero_sala', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
    ]
