# Generated by Django 5.2.8 on 2025-11-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='disponible',
        ),
    ]
