# Generated by Django 5.2.8 on 2025-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_remove_sala_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo_sala',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
